/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedAppImport } from './routes/_authenticated/_app'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthenticatedAppIndexImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppTermsImport } from './routes/_authenticated/_app/terms'
import { Route as AuthenticatedAppPrivacyImport } from './routes/_authenticated/_app/privacy'
import { Route as AuthenticatedAppTasksIndexImport } from './routes/_authenticated/_app/tasks/index'
import { Route as AuthenticatedAppStocksIndexImport } from './routes/_authenticated/_app/stocks/index'
import { Route as AuthenticatedAppSettingsIndexImport } from './routes/_authenticated/_app/settings/index'
import { Route as AuthenticatedAppOrderBookIndexImport } from './routes/_authenticated/_app/order-book/index'
import { Route as AuthenticatedAppExchangesIndexImport } from './routes/_authenticated/_app/exchanges/index'
import { Route as AuthenticatedAppDashboardIndexImport } from './routes/_authenticated/_app/dashboard/index'
import { Route as AuthenticatedAppCompaniesIndexImport } from './routes/_authenticated/_app/companies/index'
import { Route as AuthenticatedAppBotsIndexImport } from './routes/_authenticated/_app/bots/index'
import { Route as AuthenticatedAppActivityLogsIndexImport } from './routes/_authenticated/_app/activity-logs/index'
import { Route as AuthenticatedAppStocksIdImport } from './routes/_authenticated/_app/stocks/$id'
import { Route as AuthenticatedAppSettingsNotificationsIndexImport } from './routes/_authenticated/_app/settings/notifications/index'
import { Route as AuthenticatedAppSettingsDisplayIndexImport } from './routes/_authenticated/_app/settings/display/index'
import { Route as AuthenticatedAppSettingsAppearanceIndexImport } from './routes/_authenticated/_app/settings/appearance/index'
import { Route as AuthenticatedAppSettingsAccountIndexImport } from './routes/_authenticated/_app/settings/account/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAppRoute = AuthenticatedAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAppIndexRoute = AuthenticatedAppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppTermsRoute = AuthenticatedAppTermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppPrivacyRoute = AuthenticatedAppPrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppTasksIndexRoute = AuthenticatedAppTasksIndexImport.update(
  {
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any,
)

const AuthenticatedAppStocksIndexRoute =
  AuthenticatedAppStocksIndexImport.update({
    id: '/stocks/',
    path: '/stocks/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppOrderBookIndexRoute =
  AuthenticatedAppOrderBookIndexImport.update({
    id: '/order-book/',
    path: '/order-book/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppExchangesIndexRoute =
  AuthenticatedAppExchangesIndexImport.update({
    id: '/exchanges/',
    path: '/exchanges/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppDashboardIndexRoute =
  AuthenticatedAppDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppCompaniesIndexRoute =
  AuthenticatedAppCompaniesIndexImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppBotsIndexRoute = AuthenticatedAppBotsIndexImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppActivityLogsIndexRoute =
  AuthenticatedAppActivityLogsIndexImport.update({
    id: '/activity-logs/',
    path: '/activity-logs/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppStocksIdRoute = AuthenticatedAppStocksIdImport.update({
  id: '/stocks/$id',
  path: '/stocks/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppSettingsNotificationsIndexRoute =
  AuthenticatedAppSettingsNotificationsIndexImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsDisplayIndexRoute =
  AuthenticatedAppSettingsDisplayIndexImport.update({
    id: '/settings/display/',
    path: '/settings/display/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsAppearanceIndexRoute =
  AuthenticatedAppSettingsAppearanceIndexImport.update({
    id: '/settings/appearance/',
    path: '/settings/appearance/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSettingsAccountIndexRoute =
  AuthenticatedAppSettingsAccountIndexImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_app/privacy': {
      id: '/_authenticated/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedAppPrivacyImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/terms': {
      id: '/_authenticated/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedAppTermsImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app/stocks/$id': {
      id: '/_authenticated/_app/stocks/$id'
      path: '/stocks/$id'
      fullPath: '/stocks/$id'
      preLoaderRoute: typeof AuthenticatedAppStocksIdImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/activity-logs/': {
      id: '/_authenticated/_app/activity-logs/'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedAppActivityLogsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/bots/': {
      id: '/_authenticated/_app/bots/'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AuthenticatedAppBotsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/companies/': {
      id: '/_authenticated/_app/companies/'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedAppCompaniesIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/dashboard/': {
      id: '/_authenticated/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/exchanges/': {
      id: '/_authenticated/_app/exchanges/'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof AuthenticatedAppExchangesIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/order-book/': {
      id: '/_authenticated/_app/order-book/'
      path: '/order-book'
      fullPath: '/order-book'
      preLoaderRoute: typeof AuthenticatedAppOrderBookIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/stocks/': {
      id: '/_authenticated/_app/stocks/'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthenticatedAppStocksIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/tasks/': {
      id: '/_authenticated/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/account/': {
      id: '/_authenticated/_app/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/appearance/': {
      id: '/_authenticated/_app/settings/appearance/'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedAppSettingsAppearanceIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/display/': {
      id: '/_authenticated/_app/settings/display/'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedAppSettingsDisplayIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/notifications/': {
      id: '/_authenticated/_app/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppPrivacyRoute: typeof AuthenticatedAppPrivacyRoute
  AuthenticatedAppTermsRoute: typeof AuthenticatedAppTermsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppStocksIdRoute: typeof AuthenticatedAppStocksIdRoute
  AuthenticatedAppActivityLogsIndexRoute: typeof AuthenticatedAppActivityLogsIndexRoute
  AuthenticatedAppBotsIndexRoute: typeof AuthenticatedAppBotsIndexRoute
  AuthenticatedAppCompaniesIndexRoute: typeof AuthenticatedAppCompaniesIndexRoute
  AuthenticatedAppDashboardIndexRoute: typeof AuthenticatedAppDashboardIndexRoute
  AuthenticatedAppExchangesIndexRoute: typeof AuthenticatedAppExchangesIndexRoute
  AuthenticatedAppOrderBookIndexRoute: typeof AuthenticatedAppOrderBookIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppStocksIndexRoute: typeof AuthenticatedAppStocksIndexRoute
  AuthenticatedAppTasksIndexRoute: typeof AuthenticatedAppTasksIndexRoute
  AuthenticatedAppSettingsAccountIndexRoute: typeof AuthenticatedAppSettingsAccountIndexRoute
  AuthenticatedAppSettingsAppearanceIndexRoute: typeof AuthenticatedAppSettingsAppearanceIndexRoute
  AuthenticatedAppSettingsDisplayIndexRoute: typeof AuthenticatedAppSettingsDisplayIndexRoute
  AuthenticatedAppSettingsNotificationsIndexRoute: typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppPrivacyRoute: AuthenticatedAppPrivacyRoute,
  AuthenticatedAppTermsRoute: AuthenticatedAppTermsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppStocksIdRoute: AuthenticatedAppStocksIdRoute,
  AuthenticatedAppActivityLogsIndexRoute:
    AuthenticatedAppActivityLogsIndexRoute,
  AuthenticatedAppBotsIndexRoute: AuthenticatedAppBotsIndexRoute,
  AuthenticatedAppCompaniesIndexRoute: AuthenticatedAppCompaniesIndexRoute,
  AuthenticatedAppDashboardIndexRoute: AuthenticatedAppDashboardIndexRoute,
  AuthenticatedAppExchangesIndexRoute: AuthenticatedAppExchangesIndexRoute,
  AuthenticatedAppOrderBookIndexRoute: AuthenticatedAppOrderBookIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppStocksIndexRoute: AuthenticatedAppStocksIndexRoute,
  AuthenticatedAppTasksIndexRoute: AuthenticatedAppTasksIndexRoute,
  AuthenticatedAppSettingsAccountIndexRoute:
    AuthenticatedAppSettingsAccountIndexRoute,
  AuthenticatedAppSettingsAppearanceIndexRoute:
    AuthenticatedAppSettingsAppearanceIndexRoute,
  AuthenticatedAppSettingsDisplayIndexRoute:
    AuthenticatedAppSettingsDisplayIndexRoute,
  AuthenticatedAppSettingsNotificationsIndexRoute:
    AuthenticatedAppSettingsNotificationsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedAppRouteWithChildren
  '/privacy': typeof AuthenticatedAppPrivacyRoute
  '/terms': typeof AuthenticatedAppTermsRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/stocks/$id': typeof AuthenticatedAppStocksIdRoute
  '/activity-logs': typeof AuthenticatedAppActivityLogsIndexRoute
  '/bots': typeof AuthenticatedAppBotsIndexRoute
  '/companies': typeof AuthenticatedAppCompaniesIndexRoute
  '/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/exchanges': typeof AuthenticatedAppExchangesIndexRoute
  '/order-book': typeof AuthenticatedAppOrderBookIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/stocks': typeof AuthenticatedAppStocksIndexRoute
  '/tasks': typeof AuthenticatedAppTasksIndexRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/settings/appearance': typeof AuthenticatedAppSettingsAppearanceIndexRoute
  '/settings/display': typeof AuthenticatedAppSettingsDisplayIndexRoute
  '/settings/notifications': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/privacy': typeof AuthenticatedAppPrivacyRoute
  '/terms': typeof AuthenticatedAppTermsRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/stocks/$id': typeof AuthenticatedAppStocksIdRoute
  '/activity-logs': typeof AuthenticatedAppActivityLogsIndexRoute
  '/bots': typeof AuthenticatedAppBotsIndexRoute
  '/companies': typeof AuthenticatedAppCompaniesIndexRoute
  '/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/exchanges': typeof AuthenticatedAppExchangesIndexRoute
  '/order-book': typeof AuthenticatedAppOrderBookIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/stocks': typeof AuthenticatedAppStocksIndexRoute
  '/tasks': typeof AuthenticatedAppTasksIndexRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/settings/appearance': typeof AuthenticatedAppSettingsAppearanceIndexRoute
  '/settings/display': typeof AuthenticatedAppSettingsDisplayIndexRoute
  '/settings/notifications': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/privacy': typeof AuthenticatedAppPrivacyRoute
  '/_authenticated/_app/terms': typeof AuthenticatedAppTermsRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_app/stocks/$id': typeof AuthenticatedAppStocksIdRoute
  '/_authenticated/_app/activity-logs/': typeof AuthenticatedAppActivityLogsIndexRoute
  '/_authenticated/_app/bots/': typeof AuthenticatedAppBotsIndexRoute
  '/_authenticated/_app/companies/': typeof AuthenticatedAppCompaniesIndexRoute
  '/_authenticated/_app/dashboard/': typeof AuthenticatedAppDashboardIndexRoute
  '/_authenticated/_app/exchanges/': typeof AuthenticatedAppExchangesIndexRoute
  '/_authenticated/_app/order-book/': typeof AuthenticatedAppOrderBookIndexRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/stocks/': typeof AuthenticatedAppStocksIndexRoute
  '/_authenticated/_app/tasks/': typeof AuthenticatedAppTasksIndexRoute
  '/_authenticated/_app/settings/account/': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/_authenticated/_app/settings/appearance/': typeof AuthenticatedAppSettingsAppearanceIndexRoute
  '/_authenticated/_app/settings/display/': typeof AuthenticatedAppSettingsDisplayIndexRoute
  '/_authenticated/_app/settings/notifications/': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/privacy'
    | '/terms'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/stocks/$id'
    | '/activity-logs'
    | '/bots'
    | '/companies'
    | '/dashboard'
    | '/exchanges'
    | '/order-book'
    | '/settings'
    | '/stocks'
    | '/tasks'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/privacy'
    | '/terms'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/stocks/$id'
    | '/activity-logs'
    | '/bots'
    | '/companies'
    | '/dashboard'
    | '/exchanges'
    | '/order-book'
    | '/settings'
    | '/stocks'
    | '/tasks'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_app'
    | '/_authenticated/_app/privacy'
    | '/_authenticated/_app/terms'
    | '/_authenticated/_app/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_app/stocks/$id'
    | '/_authenticated/_app/activity-logs/'
    | '/_authenticated/_app/bots/'
    | '/_authenticated/_app/companies/'
    | '/_authenticated/_app/dashboard/'
    | '/_authenticated/_app/exchanges/'
    | '/_authenticated/_app/order-book/'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/stocks/'
    | '/_authenticated/_app/tasks/'
    | '/_authenticated/_app/settings/account/'
    | '/_authenticated/_app/settings/appearance/'
    | '/_authenticated/_app/settings/display/'
    | '/_authenticated/_app/settings/notifications/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth/login/",
        "/auth/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_app"
      ]
    },
    "/_authenticated/_app": {
      "filePath": "_authenticated/_app.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_app/privacy",
        "/_authenticated/_app/terms",
        "/_authenticated/_app/",
        "/_authenticated/_app/stocks/$id",
        "/_authenticated/_app/activity-logs/",
        "/_authenticated/_app/bots/",
        "/_authenticated/_app/companies/",
        "/_authenticated/_app/dashboard/",
        "/_authenticated/_app/exchanges/",
        "/_authenticated/_app/order-book/",
        "/_authenticated/_app/settings/",
        "/_authenticated/_app/stocks/",
        "/_authenticated/_app/tasks/",
        "/_authenticated/_app/settings/account/",
        "/_authenticated/_app/settings/appearance/",
        "/_authenticated/_app/settings/display/",
        "/_authenticated/_app/settings/notifications/"
      ]
    },
    "/_authenticated/_app/privacy": {
      "filePath": "_authenticated/_app/privacy.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/terms": {
      "filePath": "_authenticated/_app/terms.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/": {
      "filePath": "_authenticated/_app/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/_authenticated/_app/stocks/$id": {
      "filePath": "_authenticated/_app/stocks/$id.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/activity-logs/": {
      "filePath": "_authenticated/_app/activity-logs/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/bots/": {
      "filePath": "_authenticated/_app/bots/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/companies/": {
      "filePath": "_authenticated/_app/companies/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/dashboard/": {
      "filePath": "_authenticated/_app/dashboard/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/exchanges/": {
      "filePath": "_authenticated/_app/exchanges/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/order-book/": {
      "filePath": "_authenticated/_app/order-book/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/": {
      "filePath": "_authenticated/_app/settings/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/stocks/": {
      "filePath": "_authenticated/_app/stocks/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/tasks/": {
      "filePath": "_authenticated/_app/tasks/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/account/": {
      "filePath": "_authenticated/_app/settings/account/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/appearance/": {
      "filePath": "_authenticated/_app/settings/appearance/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/display/": {
      "filePath": "_authenticated/_app/settings/display/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/notifications/": {
      "filePath": "_authenticated/_app/settings/notifications/index.tsx",
      "parent": "/_authenticated/_app"
    }
  }
}
ROUTE_MANIFEST_END */
